In [1]:
!nvidia-smi

Fri Oct 14 08:47:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   40C    P0    35W / 250W |   1275MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:0C:00.0 Off |                    0 |
| N/A   

In [1]:
# 计算设备
import torch
from torch import nn

ModuleNotFoundError: No module named 'torch'

In [3]:
torch.device('cpu'), torch.device('cuda')

(device(type='cpu'), device(type='cuda'))

In [4]:
torch.device('cuda:1')

device(type='cuda', index=1)

In [5]:
torch.cuda.device_count()

5

现在我们定义了两个方便的函数， 这两个函数允许我们在不存在所需所有GPU的情况下运行代码。

In [6]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]"""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0),
  device(type='cuda', index=1),
  device(type='cuda', index=2),
  device(type='cuda', index=3),
  device(type='cuda', index=4)])

In [7]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [8]:
X = torch.ones(2,3, device=torch.device('cuda:2'))

In [9]:
X.device

device(type='cuda', index=2)

In [10]:
myDevice = torch.device(2)

net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=myDevice)

In [11]:
net(X)

tensor([[-0.9082],
        [-0.9082]], device='cuda:2', grad_fn=<AddmmBackward0>)

In [12]:
net[0].weight.data.device

device(type='cuda', index=2)

In [3]:
from jupyter_core.paths import jupyter_path
print(jupyter_path())

['/home/xiaoh/.local/share/jupyter', '/usr/local/share/jupyter', '/usr/share/jupyter']


数值分析作业 tmp

In [1]:
import numpy as np

In [5]:
A = np.array([[3,1,-2], [0,1,0], [1,2,6]])
A, A.shape

(array([[ 3,  1, -2],
        [ 0,  1,  0],
        [ 1,  2,  6]]),
 (3, 3))

In [8]:
B = A.T @ A
B

array([[10,  5,  0],
       [ 5,  6, 10],
       [ 0, 10, 40]])

In [12]:
c = np.linalg.eig(B)

In [15]:
np.sqrt(c[0][2])

6.540389953265458

In [16]:
np.linalg.norm(A, ord=np.inf)

9.0

In [17]:
A2 = np.array([[2,0], [0,3]])

In [18]:
A2

array([[2, 0],
       [0, 3]])

In [19]:
np.linalg.eig(A2)

(array([2., 3.]),
 array([[1., 0.],
        [0., 1.]]))